apiVersion: v1
kind: Secret

metadata:
  name: habit-secret
  namespace: habbit

type: Opaque

data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_USER: aGFiaXR1c2Vy
  MYSQL_PASSWORD: aGFiaXRwYXNzd29yZA==

  DB_USER: aGFiaXR1c2Vy
  DB_PASSWORD: aGFiaXRwYXNzd29yZA==

  JWT_SECRET: bXlzZWNyZXRrZXk=